title: FaultX‚Ä¢Docs
description: Dokumentasi Xiaomi Redmi Note 10 Pro.
# theme: just-the-docs # Local Server
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"

url: https://faultxcloud.github.io
baseurl: /fx.rn10p.docs

plugins:
  - jekyll-seo-tag 
  - jekyll-sitemap
  - jekyll-include-cache
  
aux_links:
  "üéÅ Support Me": 
    - "/fx.rn10p.docs/docs/feedback-contribution"

favicon_ico: "/assets/favicon.ico"

callouts:
  note:
    title: note
    color: blue
  warning:
    title: warning
    color: red
  important:
    title: important
    color: purple
  new:
    title: new
    color: green
  caution:
    title: caution
    color: yellow

back_to_top: true
back_to_top_text: "Back to top ‚¨Ü"

footer_content: "&copy; 2026 <a href='https://faultxcloud.github.io/faultx.link/' target='_blank'>FaultX.Repair</a>"

